media1 = int(7+8+9)/(3)
print(f'Média de 7, 8 e 9: {media1}')
media2 = int(4+5+6)/(3)
print(f'Média 4, 5 e 6: {media2}')
somaF = (media2 + media1)
print(f'Soma: {somaF}')
print(f'Média final das médias: {somaF/2}')