valor_da_hora = int(input("Valor pago pela hora trabalhada: "))
quant_horas = int(input("Quantidade de horas trabalhadas no mês: "))
salario_bruto = ( valor_da_hora * quant_horas)
fgts = (salario_bruto*0.11)
inss = (salario_bruto*0.1)
ir5 = (salario_bruto*0.05)
ir10 = (salario_bruto*0.1)
ir20 = (salario_bruto*0.2)
print(f'Salário bruto: R${salario_bruto}')
print(f'FGTS (11%): R${fgts}0')
print(f'(-) INSS (10%): R${inss}0')
if salario_bruto <= 900:
    a= (salario_bruto - (inss))
    print(f'Salario liquído: {a}0')
elif salario_bruto <= 1500:
    b5 = (inss + ir5)
    b= (salario_bruto - b5)
    print(f'(-) IR (5%): R${ir5}0')
    print(f'Total de descontos: R${b5}0')
    print(f'Salário liquído: {b}0')
elif salario_bruto <= 2500: 
    c10= (inss + ir10)
    c= (salario_bruto - c10)
    print(f'(-) IR (10%): R${ir10}0')
    print(f'Total de descontos: R${c10}0')
    print(f'Salário liquído: {c}0')
else:
    d20= (inss + ir20)
    d= (salario_bruto - d20)
    print(f'(-) IR (20%): R${ir20}0')
    print(f'Total de descontos: R$ {d20}0')
    print(f'Salário liquído: R${d}0')